version: "3.8"
        
services:
    php:
        build:
            context: ./conf
            dockerfile: project-dockerfile
        volumes:
            - "./html:/html:consistent"
        ports:
            - target: 80
              published: 8001
              mode: host
    mongodb:
        image: mongo:4.4.6
        environment:
            TZ: "Asia/Istanbul"
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
            - 27017:27017
        expose: 
            - "27017"
        volumes:
            - mongodbvol:/data/db
    redis:
        image: redis:6.0.8
        environment:
            TZ: "Asia/Istanbul"
        volumes:
            - "redisvol:/data:rw"
        expose: 
            - "6379"
        ports:
            - "6379:6379"

volumes:
    mongodbvol:
    redisvol: