version: "3.8"
        
services:
    php:
        build:
            context: ./conf
            dockerfile: project-dockerfile
        volumes:
            - "./html:/html:consistent"
        ports:
            - target: 80
              published: 8001
              mode: host
    mongodb:
        image: mongo:latest
        environment:
            TZ: "Asia/Istanbul"
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
            - 27017:27017
        expose: 
            - "27017"
        volumes:
            - mongodbvol:/data/db

volumes:
    mongodbvol: