version: "3.8"
        
services:
    nginx:
        image: nginx:latest
        environment:
            TZ: "Asia/Istanbul"
        depends_on:
            - phpfpm 
        volumes:
            - "./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf"
            - "./volumes/log/nginx:/var/log/nginx:rw"
            - "./html/dist:/www:consistent"
        ports:
            - target: 80
              published: 8001
              mode: host
    phpfpm:
        build:
            context: ./conf
            dockerfile: php-fpm-dockerfile
        volumes:
            - "./html/cgi:/cgi:consistent"
            - "./html/vendor:/vendor"
            - "./conf/settings.development.php:/etc/settings.php"
        ports:
            - "9000:9000"
    mongodb:
        image: mongo:latest
        environment:
            TZ: "Asia/Istanbul"
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
            - 27017:27017
        expose: 
            - "27017"
        volumes:
            - mongodbvol:/data/db

volumes:
    mongodbvol: